[============]DGOM: 2d convection problem
[------------]case indicator (1 parameter)
[------------]    1. case indicator  |-- 0. rotational convection
[------------]                       |-- 1. advection-diffusion
1
[============]standard element info (2 parameters)
[------------]    1. element type  |--- 2. triangle
[------------]                     |--- 3. quadrilateral
[------------]    2. order of polynomial;
2
1
[============]mesh info (3 parameters)
[------------]    1. num of elements in x direction;
[------------]    2. num of elements in y direction;
40
40
[============]time info (3 parameters)
[------------]    1. CFL number;
[------------]    2. dt;
[------------]    3. final time;
0.3
0.1
2
[============]parameters for advection-diffusion case
[------------]    1. flow rate u for x direction;
[------------]    2. flow rate v for x direction;
[------------]    3. viscosity miu;
0.5
0.5
0.01
[============]output file
[------------]    1. output file name;
[------------]    2. output time interval;
../test/Conv2d/AdvectionDiffusion/conv2d
0.001
